/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammeIndexRouteImport } from './routes/programme.index'
import { Route as ProgrammeModulesModuleIdRouteImport } from './routes/programme.modules.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeIndexRoute = ProgrammeIndexRouteImport.update({
  id: '/programme/',
  path: '/programme/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeModulesModuleIdRoute =
  ProgrammeModulesModuleIdRouteImport.update({
    id: '/programme/modules/$moduleId',
    path: '/programme/modules/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programme': typeof ProgrammeIndexRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programme/' | '/programme/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programme' | '/programme/modules/$moduleId'
  id: '__root__' | '/' | '/programme/' | '/programme/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgrammeIndexRoute: typeof ProgrammeIndexRoute
  ProgrammeModulesModuleIdRoute: typeof ProgrammeModulesModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/': {
      id: '/programme/'
      path: '/programme'
      fullPath: '/programme/'
      preLoaderRoute: typeof ProgrammeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/modules/$moduleId': {
      id: '/programme/modules/$moduleId'
      path: '/programme/modules/$moduleId'
      fullPath: '/programme/modules/$moduleId'
      preLoaderRoute: typeof ProgrammeModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgrammeIndexRoute: ProgrammeIndexRoute,
  ProgrammeModulesModuleIdRoute: ProgrammeModulesModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
