/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditIndexRouteImport } from './routes/audit.index'
import { Route as DataIntakeIndexRouteImport } from './routes/data-intake.index'
import { Route as GapAnalysisIndexRouteImport } from './routes/gap-analysis.index'
import { Route as ProgrammeIndexRouteImport } from './routes/programme.index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as RolesIndexRouteImport } from './routes/roles.index'
import { Route as SlaAnalyticsIndexRouteImport } from './routes/sla-analytics.index'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsStandardIdRouteImport } from './routes/standards.$standardId'
import { Route as WorkbenchIndexRouteImport } from './routes/workbench.index'
import { Route as DataIntakeImportImportTypeRouteImport } from './routes/data-intake.import.$importType'
import { Route as DataIntakeProposalsProposalIdRouteImport } from './routes/data-intake.proposals.$proposalId'
import { Route as ProgrammeModulesModuleIdRouteImport } from './routes/programme.modules.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntakeIndexRoute = DataIntakeIndexRouteImport.update({
  id: '/data-intake/',
  path: '/data-intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisIndexRoute = GapAnalysisIndexRouteImport.update({
  id: '/gap-analysis/',
  path: '/gap-analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeIndexRoute = ProgrammeIndexRouteImport.update({
  id: '/programme/',
  path: '/programme/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaAnalyticsIndexRoute = SlaAnalyticsIndexRouteImport.update({
  id: '/sla-analytics/',
  path: '/sla-analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsStandardIdRoute = StandardsStandardIdRouteImport.update({
  id: '/standards/$standardId',
  path: '/standards/$standardId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/workbench/',
  path: '/workbench/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntakeImportImportTypeRoute =
  DataIntakeImportImportTypeRouteImport.update({
    id: '/data-intake/import/$importType',
    path: '/data-intake/import/$importType',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataIntakeProposalsProposalIdRoute =
  DataIntakeProposalsProposalIdRouteImport.update({
    id: '/data-intake/proposals/$proposalId',
    path: '/data-intake/proposals/$proposalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammeModulesModuleIdRoute =
  ProgrammeModulesModuleIdRouteImport.update({
    id: '/programme/modules/$moduleId',
    path: '/programme/modules/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standards/$standardId': typeof StandardsStandardIdRoute
  '/audit/': typeof AuditIndexRoute
  '/data-intake/': typeof DataIntakeIndexRoute
  '/gap-analysis/': typeof GapAnalysisIndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/sla-analytics/': typeof SlaAnalyticsIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/workbench/': typeof WorkbenchIndexRoute
  '/data-intake/import/$importType': typeof DataIntakeImportImportTypeRoute
  '/data-intake/proposals/$proposalId': typeof DataIntakeProposalsProposalIdRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standards/$standardId': typeof StandardsStandardIdRoute
  '/audit': typeof AuditIndexRoute
  '/data-intake': typeof DataIntakeIndexRoute
  '/gap-analysis': typeof GapAnalysisIndexRoute
  '/programme': typeof ProgrammeIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/roles': typeof RolesIndexRoute
  '/sla-analytics': typeof SlaAnalyticsIndexRoute
  '/standards': typeof StandardsIndexRoute
  '/workbench': typeof WorkbenchIndexRoute
  '/data-intake/import/$importType': typeof DataIntakeImportImportTypeRoute
  '/data-intake/proposals/$proposalId': typeof DataIntakeProposalsProposalIdRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/standards/$standardId': typeof StandardsStandardIdRoute
  '/audit/': typeof AuditIndexRoute
  '/data-intake/': typeof DataIntakeIndexRoute
  '/gap-analysis/': typeof GapAnalysisIndexRoute
  '/programme/': typeof ProgrammeIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/sla-analytics/': typeof SlaAnalyticsIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/workbench/': typeof WorkbenchIndexRoute
  '/data-intake/import/$importType': typeof DataIntakeImportImportTypeRoute
  '/data-intake/proposals/$proposalId': typeof DataIntakeProposalsProposalIdRoute
  '/programme/modules/$moduleId': typeof ProgrammeModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/standards/$standardId'
    | '/audit/'
    | '/data-intake/'
    | '/gap-analysis/'
    | '/programme/'
    | '/reviews/'
    | '/roles/'
    | '/sla-analytics/'
    | '/standards/'
    | '/workbench/'
    | '/data-intake/import/$importType'
    | '/data-intake/proposals/$proposalId'
    | '/programme/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/standards/$standardId'
    | '/audit'
    | '/data-intake'
    | '/gap-analysis'
    | '/programme'
    | '/reviews'
    | '/roles'
    | '/sla-analytics'
    | '/standards'
    | '/workbench'
    | '/data-intake/import/$importType'
    | '/data-intake/proposals/$proposalId'
    | '/programme/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/standards/$standardId'
    | '/audit/'
    | '/data-intake/'
    | '/gap-analysis/'
    | '/programme/'
    | '/reviews/'
    | '/roles/'
    | '/sla-analytics/'
    | '/standards/'
    | '/workbench/'
    | '/data-intake/import/$importType'
    | '/data-intake/proposals/$proposalId'
    | '/programme/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StandardsStandardIdRoute: typeof StandardsStandardIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  DataIntakeIndexRoute: typeof DataIntakeIndexRoute
  GapAnalysisIndexRoute: typeof GapAnalysisIndexRoute
  ProgrammeIndexRoute: typeof ProgrammeIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  SlaAnalyticsIndexRoute: typeof SlaAnalyticsIndexRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
  DataIntakeImportImportTypeRoute: typeof DataIntakeImportImportTypeRoute
  DataIntakeProposalsProposalIdRoute: typeof DataIntakeProposalsProposalIdRoute
  ProgrammeModulesModuleIdRoute: typeof ProgrammeModulesModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-intake/': {
      id: '/data-intake/'
      path: '/data-intake'
      fullPath: '/data-intake/'
      preLoaderRoute: typeof DataIntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis/': {
      id: '/gap-analysis/'
      path: '/gap-analysis'
      fullPath: '/gap-analysis/'
      preLoaderRoute: typeof GapAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/': {
      id: '/programme/'
      path: '/programme'
      fullPath: '/programme/'
      preLoaderRoute: typeof ProgrammeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla-analytics/': {
      id: '/sla-analytics/'
      path: '/sla-analytics'
      fullPath: '/sla-analytics/'
      preLoaderRoute: typeof SlaAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$standardId': {
      id: '/standards/$standardId'
      path: '/standards/$standardId'
      fullPath: '/standards/$standardId'
      preLoaderRoute: typeof StandardsStandardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/': {
      id: '/workbench/'
      path: '/workbench'
      fullPath: '/workbench/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-intake/import/$importType': {
      id: '/data-intake/import/$importType'
      path: '/data-intake/import/$importType'
      fullPath: '/data-intake/import/$importType'
      preLoaderRoute: typeof DataIntakeImportImportTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-intake/proposals/$proposalId': {
      id: '/data-intake/proposals/$proposalId'
      path: '/data-intake/proposals/$proposalId'
      fullPath: '/data-intake/proposals/$proposalId'
      preLoaderRoute: typeof DataIntakeProposalsProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/modules/$moduleId': {
      id: '/programme/modules/$moduleId'
      path: '/programme/modules/$moduleId'
      fullPath: '/programme/modules/$moduleId'
      preLoaderRoute: typeof ProgrammeModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StandardsStandardIdRoute: StandardsStandardIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  DataIntakeIndexRoute: DataIntakeIndexRoute,
  GapAnalysisIndexRoute: GapAnalysisIndexRoute,
  ProgrammeIndexRoute: ProgrammeIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  SlaAnalyticsIndexRoute: SlaAnalyticsIndexRoute,
  StandardsIndexRoute: StandardsIndexRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
  DataIntakeImportImportTypeRoute: DataIntakeImportImportTypeRoute,
  DataIntakeProposalsProposalIdRoute: DataIntakeProposalsProposalIdRoute,
  ProgrammeModulesModuleIdRoute: ProgrammeModulesModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
