// Concept-only presentation model. Replace through adapters after the
// owner-approved PostgreSQL schema and APIs are available.
import type { AuditEventView } from "./types";

export const seedAuditEvents: AuditEventView[] = [
  {
    id: "AUD-2041",
    timestamp: "5 Aug 2026, 09:12",
    actor: "System",
    actorType: "System",
    action: "Recalculated programme RAG status",
    objectType: "Programme status",
    objectRef: "SHSIRC / BL0",
    beforeAfter: "amber -> amber",
    reason: "Scheduled rule evaluation",
    traceId: "trc-7f31a0",
  },
  {
    id: "AUD-2038",
    timestamp: "4 Aug 2026, 16:40",
    actor: "System Agent",
    actorType: "Agent",
    action: "Created draft SOP mapping",
    objectType: "Agent run",
    objectRef: "RUN-2026-0814-A",
    beforeAfter: "none -> DRAFT (24 mappings, 6 no-match)",
    reason: "Requested from AI Workbench",
    traceId: "trc-7f2ee1",
    promptHash: "sha256:4f19c2a8...e701",
  },
  {
    id: "AUD-2036",
    timestamp: "4 Aug 2026, 16:41",
    actor: "System",
    actorType: "System",
    action: "Rejected citation outside demo whitelist",
    objectType: "Mapping citation",
    objectRef: "REV-0094 / clause 7",
    beforeAfter: "suggested -> auto-rejected",
    reason: "Citation ID not present in the demo whitelist",
    traceId: "trc-7f2ee4",
  },
  {
    id: "AUD-2031",
    timestamp: "3 Aug 2026, 08:05",
    actor: "M365 Sync",
    actorType: "Sync",
    action: "Synchronised work package dates",
    objectType: "Work package",
    objectRef: "M03 / 7 records",
    beforeAfter: "4 dates updated",
    reason: "Scheduled synchronisation",
    traceId: "trc-7f1c73",
  },
  {
    id: "AUD-2028",
    timestamp: "2 Aug 2026, 14:02",
    actor: "System Agent",
    actorType: "Agent",
    action: "Created draft gap matrix",
    objectType: "Gap analysis",
    objectRef: "GAP-2026-0802-ICU",
    beforeAfter: "v0.3 -> v0.4 (DRAFT)",
    reason: "Requested from AI Workbench",
    traceId: "trc-7f0aa2",
    promptHash: "sha256:9ab34c17...4d02",
  },
  {
    id: "AUD-2025",
    timestamp: "1 Aug 2026, 11:20",
    actor: "Dr. Maya Rahman",
    actorType: "Human",
    action: "Approved gap matrix row",
    objectType: "Gap matrix row",
    objectRef: "GAP-2026-0802-ICU / ICU-R05",
    beforeAfter: "Not reviewed -> Approved",
    reason: "Protocol and completed records verified",
    traceId: "trc-7ef991",
  },
  {
    id: "AUD-2022",
    timestamp: "31 Jul 2026, 09:44",
    actor: "Dr. Maya Rahman",
    actorType: "Human",
    action: "Returned draft mapping for correction",
    objectType: "Review item",
    objectRef: "REV-0088",
    beforeAfter: "Awaiting review -> Returned for correction",
    reason: "Two clauses cite a standard outside the ICU scope",
    traceId: "trc-7ee410",
  },
  {
    id: "AUD-2019",
    timestamp: "30 Jul 2026, 17:12",
    actor: "Nabila Chowdhury",
    actorType: "Human",
    action: "Recorded man-day entry",
    objectType: "Effort entry",
    objectRef: "EFF-0771 (M03)",
    beforeAfter: "none -> 6.0 synthetic man-days",
    reason: "Original entry",
    traceId: "trc-7ed220",
  },
  {
    id: "AUD-2020",
    timestamp: "30 Jul 2026, 17:26",
    actor: "Nabila Chowdhury",
    actorType: "Human",
    action: "Posted reversing entry",
    objectType: "Effort entry",
    objectRef: "EFF-0772 reverses EFF-0771",
    beforeAfter: "reversal -> -6.0 synthetic man-days",
    reason: "Original entry booked against the wrong module",
    traceId: "trc-7ed220",
  },
  {
    id: "AUD-2021",
    timestamp: "30 Jul 2026, 17:28",
    actor: "Nabila Chowdhury",
    actorType: "Human",
    action: "Recorded corrected man-day entry",
    objectType: "Effort entry",
    objectRef: "EFF-0773 (M04)",
    beforeAfter: "none -> 6.0 synthetic man-days",
    reason: "Corrected entry after reversal",
    traceId: "trc-7ed220",
  },
];

export const auditSummary = { human: 6, agent: 2, sync: 1, rejectedCitation: 1 };

export const correctionTrace = "trc-7ed220";