// Concept-only presentation model. Programme-wide authoritative input register.
// No files are stored: a production backend must validate file type, malware
// scanning, size, checksum, classification and retention before storing files.
import type { PacketId } from "./readiness";

export type EvidenceState =
  | "Missing"
  | "Received - unverified"
  | "Needs correction"
  | "Ready for review"
  | "Accepted";

export type DocumentLevel = "L0" | "L1" | "L2" | "L3";

export interface EvidenceArtifact {
  id: string;
  title: string;
  requiredBy: PacketId;
  ownerRole: string;
  owner: string;
  classification: string;
  version: string;
  checksum: string;
  level: DocumentLevel;
  parentRef: string;
  modules: string[];
  state: EvidenceState;
  note: string;
  attestedBy: string;
  attestedAt: string;
  reference: string;
  requiredChecks: string[];
  intakeLink?: string;
}

const NONE = "Not recorded";

export const seedEvidenceRegister: EvidenceArtifact[] = [
  {
    id: "ART-01",
    title: "Implementation Guide",
    requiredBy: "sprint-0",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L0",
    parentRef: "None - root document",
    modules: ["Programme"],
    state: "Received - unverified",
    note: "Draft copy circulated by email; authoritative version and owner signature outstanding.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: "External reference: programme SharePoint (placeholder)",
    requiredChecks: ["Named owner", "Version control", "Approval signature"],
  },
  {
    id: "ART-02",
    title: "Baseline migration 0000",
    requiredBy: "sprint-0",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Technical - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-01",
    modules: ["Platform"],
    state: "Missing",
    note: "Authoritative migration source not confirmed (OD-A).",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Source of record confirmed", "Checksum recorded", "Applies cleanly to empty database"],
  },
  {
    id: "ART-03",
    title: "Baseline migration 0001",
    requiredBy: "sprint-0",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Technical - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-02",
    modules: ["Platform"],
    state: "Missing",
    note: "Depends on migration 0000 being confirmed first.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Ordered after 0000", "Checksum recorded", "Reversible or documented forward-only"],
  },
  {
    id: "ART-04",
    title: "Roles and grants evidence",
    requiredBy: "sprint-0",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Security - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-03",
    modules: ["Platform"],
    state: "Missing",
    note: "Grant listing per public table required for every role.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Grant listing per table", "Least-privilege review", "Reviewer sign-off"],
  },
  {
    id: "ART-05",
    title: "smoke_test script and result",
    requiredBy: "sprint-0",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Technical - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-03",
    modules: ["Platform"],
    state: "Missing",
    note: "No run output provided. Not run in this mockup.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Script under version control", "Run output captured", "Executed against baseline schema"],
  },
  {
    id: "ART-06",
    title: "SCH-001 schedule",
    requiredBy: "sprint-0",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "v0.9 (placeholder)",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-01",
    modules: ["Programme"],
    state: "Received - unverified",
    note: "Visual representation only; authoritative export not verified.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: "Related Data Intake receipt: RCP-0039 (synthetic)",
    requiredChecks: ["Authoritative export", "Baseline identifier", "Owner attestation"],
    intakeLink: "/data-intake",
  },
  {
    id: "ART-07",
    title: "Dependency register",
    requiredBy: "sprint-0",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-06",
    modules: ["Programme"],
    state: "Needs correction",
    note: "Placeholder rows contain no predecessor identifiers.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: "Related Data Intake receipt: RCP-0040 (synthetic)",
    requiredChecks: ["Predecessor identifiers", "Lag and type", "Cross-module dependencies"],
    intakeLink: "/data-intake",
  },
  {
    id: "ART-08",
    title: "Milestone and mission register",
    requiredBy: "sprint-0",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-06",
    modules: ["Programme"],
    state: "Missing",
    note: "Milestone list not supplied from the authoritative schedule.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Milestone identifiers", "Baseline dates", "Accountable owner per milestone"],
  },
  {
    id: "ART-09",
    title: "30-module registry",
    requiredBy: "sprint-0",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "synthetic-1",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-01",
    modules: ["All modules"],
    state: "Received - unverified",
    note: "Registry in the mockup is synthetic; authoritative module list not confirmed.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: "Registry change proposals in Data Intake (synthetic)",
    requiredChecks: ["Module codes match source", "Estate mapping", "Owner per module"],
    intakeLink: "/data-intake",
  },
  {
    id: "ART-10",
    title: "BL0 freeze record",
    requiredBy: "sprint-0",
    ownerRole: "Executive Sponsor",
    owner: "Dr Saleha Chowdhury",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-06",
    modules: ["Programme"],
    state: "Missing",
    note: "Baseline freeze cannot be attested until SCH-001 is verified.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Freeze date", "Scope statement", "Sponsor signature"],
  },
  {
    id: "ART-11",
    title: "JCI corpus manifest: 18 chapters + 2 appendices",
    requiredBy: "sprint-1",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Licensed - access controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-01",
    modules: ["Standards"],
    state: "Missing",
    note: "0 of 20 production source units received. Licensed content is not present in this mockup.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["20 source units listed", "Edition and version", "Licence position confirmed"],
  },
  {
    id: "ART-12",
    title: "JCI 262-ID whitelist (valid_ids)",
    requiredBy: "sprint-1",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Licensed - access controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-11",
    modules: ["Standards"],
    state: "Missing",
    note: "0 / 262 identifiers verified. Validation not run.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Exactly 262 identifiers", "No unknown identifiers", "Version pinned to manifest"],
  },
  {
    id: "ART-13",
    title: "7th-to-8th-edition crosswalk",
    requiredBy: "sprint-1",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Licensed - access controlled",
    version: "concept only",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-11",
    modules: ["Standards"],
    state: "Needs correction",
    note: "Concept representation only; coverage not assessed.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Coverage per identifier", "Unmapped identifiers listed", "Reviewer sign-off"],
  },
  {
    id: "ART-14",
    title: "check_citations.py validation evidence",
    requiredBy: "sprint-1",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Technical - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L3",
    parentRef: "ART-12",
    modules: ["Standards"],
    state: "Missing",
    note: "Whitelist validation has not been run against a production corpus.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Run output captured", "Quarantine list", "Rerun after corpus change"],
  },
  {
    id: "ART-15",
    title: "Retrieval model registry",
    requiredBy: "sprint-2",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Technical - restricted",
    version: "placeholder",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Standards", "Workbench"],
    state: "Missing",
    note: "Placeholder configuration only; no approved production entry.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Approved configuration", "Owner and change reason", "Version history"],
  },
  {
    id: "ART-16",
    title: "Fixed 100-query evaluation set",
    requiredBy: "sprint-2",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-11",
    modules: ["Standards"],
    state: "Missing",
    note: "0 of 100 production queries available. Evaluation not run.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["100 fixed queries", "Expected results per query", "Frozen between runs"],
  },
  {
    id: "ART-17",
    title: "20-SOP gold set",
    requiredBy: "sprint-3",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Internal - clinical controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Workbench"],
    state: "Missing",
    note: "0 of 20 production SOPs received. Precision gate cannot be measured.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["20 approved SOPs", "Expected mappings per clause", "Clinical reviewer agreement"],
  },
  {
    id: "ART-18",
    title: "Named reviewer roster and capacity",
    requiredBy: "sprint-3",
    ownerRole: "Clinical / Quality Reviewer",
    owner: "Dr Farhana Kabir",
    classification: "Internal - HR sensitive",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Reviews"],
    state: "Needs correction",
    note: "Roster pending (OD-C); capacity per reviewer not stated.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Named reviewers", "Weekly capacity", "Segregation-of-duties mapping"],
  },
  {
    id: "ART-19",
    title: "Excel review workbook specification",
    requiredBy: "sprint-3",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "Internal - programme controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Reviews"],
    state: "Missing",
    note: "Round-trip specification not represented in the mockup.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Protected identifier columns", "Version stamp", "Decision value vocabulary"],
  },
  {
    id: "ART-20",
    title: "run_gap_analysis.py or equivalent run specification",
    requiredBy: "sprint-4",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Technical - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Gap Analysis"],
    state: "Missing",
    note: "Run specification and lineage fields not defined.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Deterministic inputs", "Run ID and prompt hash", "Reproducible output"],
  },
  {
    id: "ART-21",
    title: "Authoritative DGHS source set",
    requiredBy: "sprint-4",
    ownerRole: "Programme PMO",
    owner: "Nadia Rahman",
    classification: "External - public regulation",
    version: "placeholder",
    checksum: "sha256:<placeholder>",
    level: "L1",
    parentRef: "ART-01",
    modules: ["Gap Analysis"],
    state: "Needs correction",
    note: "Placeholder records only; source definition outstanding (OD-D).",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Document list and versions", "Publication references", "Owner per document"],
  },
  {
    id: "ART-22",
    title: "Real ICU source-document pack",
    requiredBy: "sprint-4",
    ownerRole: "Module Lead",
    owner: "Rezaul Karim",
    classification: "Internal - clinical controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-20",
    modules: ["M03 ICU"],
    state: "Missing",
    note: "Gap analysis currently runs on synthetic inputs only.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Approved document list", "Classification and retention", "Owner attestation"],
  },
  {
    id: "ART-23",
    title: "Real IPC source-document pack",
    requiredBy: "sprint-4",
    ownerRole: "Module Lead",
    owner: "Rezaul Karim",
    classification: "Internal - clinical controlled",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-20",
    modules: ["Infection prevention"],
    state: "Missing",
    note: "Gap analysis currently runs on synthetic inputs only.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Approved document list", "Classification and retention", "Owner attestation"],
  },
  {
    id: "ART-24",
    title: "Backup and restore procedure and test evidence",
    requiredBy: "sprint-0",
    ownerRole: "Auditor / System Steward",
    owner: "Tanvir Alam",
    classification: "Security - restricted",
    version: "v-pending",
    checksum: "sha256:<placeholder>",
    level: "L2",
    parentRef: "ART-01",
    modules: ["Platform"],
    state: "Missing",
    note: "Procedure not represented; restore test not run.",
    attestedBy: NONE,
    attestedAt: NONE,
    reference: NONE,
    requiredChecks: ["Documented procedure", "Successful restore test", "Retention statement"],
  },
];

export const evidenceStates: EvidenceState[] = [
  "Missing",
  "Received - unverified",
  "Needs correction",
  "Ready for review",
  "Accepted",
];

export const documentLevels: DocumentLevel[] = ["L0", "L1", "L2", "L3"];

/** Evidence that is acceptable for a gate: attested ready for review or accepted. */
export function isGateReady(state: EvidenceState) {
  return state === "Ready for review" || state === "Accepted";
}

export function evidenceStateTone(state: EvidenceState) {
  switch (state) {
    case "Accepted":
      return "success" as const;
    case "Ready for review":
      return "info" as const;
    case "Received - unverified":
    case "Needs correction":
      return "warning" as const;
    default:
      return "danger" as const;
  }
}