// Concept-only presentation model. Replace through adapters after the
// owner-approved PostgreSQL schema and APIs are available.
import type { GapAnalysisSummary, GapMatrixRowView } from "./types";

const icuRows: GapMatrixRowView[] = [
  {
    id: "ICU-R01",
    requirementId: "DEMO-JCI-014",
    summary: "Critical-care staff competency evidence",
    currentEvidence: "No competency records received for the ICU establishment.",
    citation: "-",
    state: "Absent",
    confidence: 0.91,
    proposedModule: "M03",
    proposedOwner: "Nabila Chowdhury",
    nextAction: "Request the competency matrix and attestation records from nursing leadership.",
    reviewStatus: "Not reviewed",
    whyAssigned: "No document in the synthetic input set contains competency attestation records.",
    missingEvidence: ["Competency matrix", "Signed attestation records"],
    inputDocuments: ["SYN-DOC-0417", "SYN-DOC-0442"],
  },
  {
    id: "ICU-R02",
    requirementId: "DEMO-JCI-027",
    summary: "High-alert medication double-check documentation",
    currentEvidence: "Double-check recorded in 2 of 4 sampled synthetic shifts.",
    citation: "SYN-DOC-0442, p.3",
    state: "Partial",
    confidence: 0.86,
    proposedModule: "M03",
    proposedOwner: "Dr. Maya Rahman",
    nextAction: "Standardise the administration record field and re-sample after two weeks.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Evidence exists but does not cover all sampled shifts in the synthetic set.",
    missingEvidence: ["Night-shift administration records"],
    inputDocuments: ["SYN-DOC-0442"],
  },
  {
    id: "ICU-R03",
    requirementId: "DEMO-JCI-041",
    summary: "Isolation-room environmental monitoring records",
    currentEvidence: "No monitoring logs supplied for the ICU isolation rooms.",
    citation: "-",
    state: "Absent",
    confidence: 0.88,
    proposedModule: "M03",
    proposedOwner: "Sara Karim",
    nextAction: "Confirm the monitoring method and start a dated log before Gate 1.",
    reviewStatus: "Not reviewed",
    whyAssigned: "The requirement expects retained parameter records; none appear in the input set.",
    missingEvidence: ["Pressure and air-change logs", "Calibration record"],
    inputDocuments: ["SYN-DOC-0463"],
  },
  {
    id: "ICU-R04",
    requirementId: "DEMO-JCI-033",
    summary: "Emergency equipment readiness logs",
    currentEvidence: "Checklist supplied but signatures are not legible in the synthetic scan.",
    citation: "SYN-DOC-0451, p.2",
    state: "Present - unverified",
    confidence: 0.72,
    proposedModule: "M03",
    proposedOwner: "Dr. Arif Hasan",
    nextAction: "Re-supply a verifiable copy and confirm the checking authority.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Document is present but attribution cannot be verified from the input.",
    missingEvidence: ["Legible signature or system record"],
    inputDocuments: ["SYN-DOC-0451"],
  },
  {
    id: "ICU-R05",
    requirementId: "DEMO-JCI-002",
    summary: "Structured clinical handover records",
    currentEvidence: "Handover protocol and completed sample forms supplied.",
    citation: "SYN-DOC-0417, p.1-4",
    state: "Present",
    confidence: 0.94,
    proposedModule: "M03",
    proposedOwner: "Dr. Arif Hasan",
    nextAction: "No action. Retain for the Gate 1 evidence pack.",
    reviewStatus: "Approved",
    whyAssigned: "Protocol and completed records both appear in the input set.",
    missingEvidence: [],
    inputDocuments: ["SYN-DOC-0417"],
  },
  {
    id: "ICU-R06",
    requirementId: "DEMO-JCI-052",
    summary: "Sedation monitoring competency attestation",
    currentEvidence: "No attestation records received.",
    citation: "-",
    state: "Absent",
    confidence: 0.83,
    proposedModule: "M03",
    proposedOwner: "Nabila Chowdhury",
    nextAction: "Add sedation attestation to the competency evidence request.",
    reviewStatus: "Not reviewed",
    whyAssigned: "No attestation document is present in the synthetic input set.",
    missingEvidence: ["Sedation attestation register"],
    inputDocuments: ["SYN-DOC-0442"],
  },
  {
    id: "ICU-R07",
    requirementId: "DEMO-DGHS-003",
    summary: "Ventilator preventive maintenance schedule",
    currentEvidence: "Schedule supplied with completed entries for two quarters.",
    citation: "SYN-DOC-0460, p.6",
    state: "Present",
    confidence: 0.9,
    proposedModule: "M11",
    proposedOwner: "Omar Siddiqui",
    nextAction: "No action. Cross-reference with equipment commissioning records.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Schedule and completion entries are both present.",
    missingEvidence: [],
    inputDocuments: ["SYN-DOC-0460"],
  },
  {
    id: "ICU-R08",
    requirementId: "DEMO-JCI-019",
    summary: "Infection surveillance escalation records",
    currentEvidence: "Escalation noted for one event; timing evidence incomplete.",
    citation: "SYN-DOC-0463, p.9",
    state: "Partial",
    confidence: 0.69,
    proposedModule: "M03",
    proposedOwner: "Sara Karim",
    nextAction: "Record escalation timestamps and the receiving authority.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Escalation is documented but the required timing evidence is missing.",
    missingEvidence: ["Escalation timestamps"],
    inputDocuments: ["SYN-DOC-0463"],
  },
];

const ipcRows: GapMatrixRowView[] = [
  {
    id: "IPC-R01",
    requirementId: "DEMO-JCI-008",
    summary: "Hand-hygiene audit follow-up",
    currentEvidence: "Audit results supplied; corrective actions not tracked to closure.",
    citation: "SYN-DOC-0470, p.2",
    state: "Partial",
    confidence: 0.87,
    proposedModule: "M04",
    proposedOwner: "Sara Karim",
    nextAction: "Add a corrective-action tracker with owners and due dates.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Audit evidence present, follow-up evidence absent.",
    missingEvidence: ["Corrective action tracker"],
    inputDocuments: ["SYN-DOC-0470"],
  },
  {
    id: "IPC-R02",
    requirementId: "DEMO-JCI-005",
    summary: "Infection prevention programme scope statement",
    currentEvidence: "Approved programme scope document supplied.",
    citation: "SYN-DOC-0468, p.1",
    state: "Present",
    confidence: 0.93,
    proposedModule: "M04",
    proposedOwner: "Sara Karim",
    nextAction: "No action. Retain for the Gate 1 evidence pack.",
    reviewStatus: "Approved",
    whyAssigned: "Scope document with leadership approval is present.",
    missingEvidence: [],
    inputDocuments: ["SYN-DOC-0468"],
  },
  {
    id: "IPC-R03",
    requirementId: "DEMO-JCI-019",
    summary: "Surveillance escalation thresholds defined",
    currentEvidence: "Thresholds drafted but not approved.",
    citation: "SYN-DOC-0471, p.4",
    state: "Partial",
    confidence: 0.78,
    proposedModule: "M04",
    proposedOwner: "Sara Karim",
    nextAction: "Submit thresholds for clinical governance approval.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Draft exists without approval evidence.",
    missingEvidence: ["Approval minute"],
    inputDocuments: ["SYN-DOC-0471"],
  },
  {
    id: "IPC-R04",
    requirementId: "DEMO-JCI-041",
    summary: "Isolation-room environmental monitoring records",
    currentEvidence: "No logs supplied for general isolation rooms.",
    citation: "-",
    state: "Absent",
    confidence: 0.85,
    proposedModule: "M04",
    proposedOwner: "Sara Karim",
    nextAction: "Start dated monitoring logs across all isolation rooms.",
    reviewStatus: "Not reviewed",
    whyAssigned: "No monitoring records appear in the input set.",
    missingEvidence: ["Monitoring logs"],
    inputDocuments: ["SYN-DOC-0470", "SYN-DOC-0471"],
  },
  {
    id: "IPC-R05",
    requirementId: "DEMO-DGHS-007",
    summary: "Biomedical waste segregation procedure",
    currentEvidence: "Procedure supplied; training records not verifiable.",
    citation: "SYN-DOC-0474, p.3",
    state: "Present - unverified",
    confidence: 0.7,
    proposedModule: "M26",
    proposedOwner: "Sara Karim",
    nextAction: "Supply the waste-handling training register.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Procedure present but supporting training evidence unverified.",
    missingEvidence: ["Training register"],
    inputDocuments: ["SYN-DOC-0474"],
  },
  {
    id: "IPC-R06",
    requirementId: "DEMO-JCI-061",
    summary: "Infection-related safety event reporting",
    currentEvidence: "Reporting route documented with two sampled reports.",
    citation: "SYN-DOC-0476, p.5",
    state: "Present",
    confidence: 0.89,
    proposedModule: "M15",
    proposedOwner: "Dr. Maya Rahman",
    nextAction: "No action. Include in the quality evidence pack.",
    reviewStatus: "Not reviewed",
    whyAssigned: "Route and sample reports are both present.",
    missingEvidence: [],
    inputDocuments: ["SYN-DOC-0476"],
  },
];

function counts(rows: GapMatrixRowView[]) {
  return {
    present: rows.filter((r) => r.state === "Present").length,
    partial: rows.filter((r) => r.state === "Partial").length,
    absent: rows.filter((r) => r.state === "Absent").length,
    unverified: rows.filter((r) => r.state === "Present - unverified").length,
  };
}

export const gapAnalyses: GapAnalysisSummary[] = [
  {
    id: "icu-readiness",
    name: "ICU Readiness - Draft gap matrix",
    moduleCode: "M03",
    scope: "Synthetic comparison against placeholder JCI and DGHS requirements",
    version: "v0.4",
    lastRun: "2 Aug 2026, 14:02",
    documentsAssessed: 6,
    ...counts(icuRows),
    ownerReviewState: "Awaiting owner acceptance",
    runId: "GAP-2026-0802-ICU",
    model: "local-mistral-demo-ref (Demo)",
    promptHash: "sha256:9ab34c17...4d02",
    rows: icuRows,
  },
  {
    id: "infection-prevention",
    name: "Infection Prevention - Draft gap matrix",
    moduleCode: "M04",
    scope: "Synthetic comparison against placeholder JCI and DGHS requirements",
    version: "v0.3",
    lastRun: "1 Aug 2026, 10:47",
    documentsAssessed: 5,
    ...counts(ipcRows),
    ownerReviewState: "In reviewer queue",
    runId: "GAP-2026-0801-IPC",
    model: "local-mistral-demo-ref (Demo)",
    promptHash: "sha256:1c7f88de...b310",
    rows: ipcRows,
  },
];

export function gapAnalysisById(id: string) {
  return gapAnalyses.find((g) => g.id === id);
}