// Concept-only presentation model. Replace through adapters after the
// owner-approved PostgreSQL schema and APIs are available.
import type { ReviewQueueItem } from "./types";

export const reviewQueue: ReviewQueueItem[] = [
  {
    id: "REV-0091",
    item: "ICU Medication Management SOP v0.3 - draft mapping",
    moduleCode: "M03",
    draftType: "SOP to standards mapping",
    submittedBy: "System Agent",
    submitted: "4 Aug 2026",
    due: "7 Aug 2026",
    effort: "~35 min (30 clauses)",
    citation: "Valid",
    status: "Awaiting review",
    overdue: false,
  },
  {
    id: "REV-0092",
    item: "ICU Readiness gap matrix v0.4 - row assignments",
    moduleCode: "M03",
    draftType: "Gap matrix review",
    submittedBy: "System Agent",
    submitted: "2 Aug 2026",
    due: "4 Aug 2026",
    effort: "~20 min (12 rows)",
    citation: "Valid",
    status: "Awaiting review",
    overdue: true,
  },
  {
    id: "REV-0093",
    item: "Hand Hygiene Monitoring SOP v0.2 - draft mapping",
    moduleCode: "M04",
    draftType: "SOP to standards mapping",
    submittedBy: "System Agent",
    submitted: "3 Aug 2026",
    due: "8 Aug 2026",
    effort: "~18 min (18 clauses)",
    citation: "Valid",
    status: "Awaiting review",
    overdue: false,
    stale: true,
  },
  {
    id: "REV-0088",
    item: "Critical Care Competency SOP v0.1 - draft mapping",
    moduleCode: "M07",
    draftType: "SOP to standards mapping",
    submittedBy: "System Agent",
    submitted: "28 Jul 2026",
    due: "31 Jul 2026",
    effort: "~22 min (22 clauses)",
    citation: "Valid",
    status: "Returned for correction",
    reason: "Two clauses cite a standard outside the ICU scope. Re-run with the corrected scope.",
    overdue: false,
  },
  {
    id: "REV-0094",
    item: "Facility fire-system mapping draft",
    moduleCode: "M17",
    draftType: "SOP to standards mapping",
    submittedBy: "System Agent",
    submitted: "4 Aug 2026",
    due: "8 Aug 2026",
    effort: "Blocked",
    citation: "Invalid",
    status: "Auto-rejected",
    reason: "Citation validation failed: referenced ID is not in the demo whitelist.",
    overdue: false,
  },
  {
    id: "REV-0085",
    item: "IPC surveillance escalation mapping",
    moduleCode: "M04",
    draftType: "SOP to standards mapping",
    submittedBy: "System Agent",
    submitted: "24 Jul 2026",
    due: "27 Jul 2026",
    effort: "Complete",
    citation: "Valid",
    status: "Approved",
    overdue: false,
  },
];

export const reviewSummary = {
  awaiting: 3,
  returned: 1,
  approvedThisWeek: 7,
  oldestDays: 2,
};

export const reviewers = ["Dr. Maya Rahman", "Sara Karim", "Dr. Arif Hasan", "Nabila Chowdhury"];